#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Size
version:      0.59
version_from: Size.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
