abstract: Perl extension for finding the memory usage of Perl variables
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Devel-Size
no_index: 
  directory: 
    - examples
    - inc
    - t
recommends: 
  Devel::Size::Report: 0.11
requires: 
  DynaLoader: 0
version: 0.65
